

services:
  nginx:
    container_name: web
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./projectSrc:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: fpm
    image: php:8.3-fpm
    volumes:
      - ./projectSrc:/var/www
    working_dir: /var/www