

services:
  nginx:
    container_name: web
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./projectSrc:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./projectSrc:/var/www
    working_dir: /var/www

  postgres:
    container_name: db
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=php-app
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pguser
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - ./docker/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docker/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    tmpfs:
      - /var/lib/postgresql/data

  mailer:
    container_name: mailer
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"